import time


def format_time(timestamp):
    '''
    Args:
        timestamp: a float number generated by using 'time.time()' method
    Returns:
        timestamp_formatted: a formatted string readable to man, default
        format is "%Y-%m-%d %H:%M:%S", e.g: 2019-01-01 23:59:59
    '''
    if int(timestamp) < 0:
        raise ValueError("wrong timestamp value!")
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(timestamp))


